version: "3.7"

services:
  postgres:
    container_name: postgres-ilumeo
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ilupoint
    volumes:
      - ilupoint_pg_data:/var/lib/postgres/data

volumes:
  ilupoint_pg_data:
