version: "3.7"

services:
  postgres:
    container_name: postgres-ilumeo
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ilupoint
    volumes:
      - ilupoint_pg_data:/var/lib/postgres/data

  api-ilumeo:
    container_name: api-ilumeo
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - APPLICATION_NAME=ILUMEO-API
      - APPLICATION_PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=ilupoint
    depends_on:
      - postgres

volumes:
  ilupoint_pg_data:
